### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Waterovsky** [Stimayk/OfficialDsStatus-CS2#1]
In my case, the plugin works fine after server restart, but it stops working after map change - then it's not possible to join the game from Steam/in-game friends list.

**Comment by Stimayk** [comment]
Check the latest version

**Comment by Waterovsky** [comment]
It seems to be working correctly now, but wouldn't it be more logical to use the OnMapStart function (I'm not sure if it exists in CSS) instead of OnRoundStart?

**Comment by AkBk201** [comment]
1 раз появилась кнопка "присоединиться" и то не вышло, хотя север бул пустой...

**Comment by Stimayk** [comment]
> 1 раз появилась кнопка "присоединиться" и то не вышло, хотя север бул пустой...

Проверьте указан ли токен.
